'use client'

import { FormEvent, useState } from 'react'
import { Building2, Search, Sparkles } from 'lucide-react'
import AppShell from '@/components/AppShell'
import RequireAuth from '@/components/RequireAuth'
import { api } from '@/lib/api'

export default function CompanyIntelPage() { const [name, setName] = useState(''); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); if (!name.trim()) return; setLoading(true); setError(''); try { setResult(await api.company.search(name)) } catch (err) { setError(err instanceof Error ? err.message : 'Company research failed.') } finally { setLoading(false) } } return <RequireAuth><AppShell><section className="page-heading"><p className="eyebrow">COMPANY INTELLIGENCE</p><h1>Walk into every company conversation prepared.</h1><p>Search the company records already gathered by TalentRadar.</p></section><form className="search-form compact-search" onSubmit={submit}><Search size={20}/><input value={name} onChange={e => setName(e.target.value)} placeholder="Company name, e.g. Razorpay" /><button className="primary-button" disabled={loading}>{loading ? 'Researching…' : 'Research company'}</button></form>{error && <p className="form-error">{error}</p>}{result ? <section className="intel-result"><div className="intel-heading"><div className="company-logo rose"><Building2 size={17}/></div><div><p className="eyebrow">COMPANY RECORD</p><h2>{String(result.name || result.company_name || name)}</h2></div></div><pre className="generated-copy">{JSON.stringify(result, null, 2)}</pre></section> : <div className="empty-state"><Sparkles size={24}/><h2>Research a company before you apply.</h2><p>Enter a company name to view its profile and open roles from your backend data.</p></div>}</AppShell></RequireAuth> }
