'use client'

import { FormEvent, useState } from 'react'
import { FileText, Sparkles, WandSparkles } from 'lucide-react'
import AppShell from '@/components/AppShell'
import RequireAuth from '@/components/RequireAuth'
import { api } from '@/lib/api'

type Mode = 'analyze' | 'tailor' | 'cover'
export default function ResumeStudioPage() { const [mode, setMode] = useState<Mode>('analyze'); const [resume, setResume] = useState(''); const [job, setJob] = useState(''); const [title, setTitle] = useState(''); const [company, setCompany] = useState(''); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(''); setResult(null); try { const common = { resume_text: resume, job_description: job, job_title: title || undefined }; const response = mode === 'analyze' ? await api.resumes.analyze(common) : mode === 'tailor' ? await api.resumes.tailor(common) : await api.resumes.coverLetter({ ...common, job_title: title, company, tone: 'professional' }); setResult(response) } catch (err) { setError(err instanceof Error ? err.message : 'Resume request failed.') } finally { setLoading(false) } } return <RequireAuth><AppShell><section className="page-heading"><p className="eyebrow">RESUME STUDIO</p><h1>Turn your experience into a stronger yes.</h1><p>Run ATS analysis, tailor your resume, or write a targeted cover letter with the backend AI tools.</p></section><div className="studio-tabs">{([['analyze', 'ATS analysis', FileText], ['tailor', 'Tailor resume', WandSparkles], ['cover', 'Cover letter', Sparkles]] as const).map(([key, label, Icon]) => <button key={key} className={mode === key ? 'selected' : ''} onClick={() => { setMode(key); setResult(null) }}><Icon size={16}/>{label}</button>)}</div><div className="studio-grid"><form className="resume-form" onSubmit={submit}><label>Your resume text<textarea value={resume} onChange={e => setResume(e.target.value)} required placeholder="Paste your current resume here…" /></label><label>Target job description<textarea value={job} onChange={e => setJob(e.target.value)} required placeholder="Paste the job description you want to target…" /></label><div className="inline-fields"><label>Job title<input value={title} onChange={e => setTitle(e.target.value)} required={mode === 'cover'} placeholder="e.g. Product Designer" /></label>{mode === 'cover' && <label>Company<input value={company} onChange={e => setCompany(e.target.value)} required placeholder="e.g. Miro" /></label>}</div>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={loading}>{loading ? 'Working on it…' : mode === 'analyze' ? 'Analyze my resume' : mode === 'tailor' ? 'Tailor my resume' : 'Generate cover letter'}</button></form><aside className="result-panel"><p className="eyebrow">RESULT</p>{!result ? <div className="result-empty"><Sparkles size={24}/><h2>Ready when you are.</h2><p>Your analysis or generated content will appear here.</p></div> : <Result result={result}/>}</aside></div></AppShell></RequireAuth> }
function Result({ result }: { result: Record<string, unknown> }) { const content = typeof result.content === 'string' ? result.content : null; return content ? <pre className="generated-copy">{content}</pre> : <pre className="generated-copy">{JSON.stringify(result, null, 2)}</pre> }
