"""
services/company_contacts.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Talent/recruiting contacts for the Company Intelligence panel.

Three things live here, and the split matters:

``list_contacts``      reads what is already stored — curated public channels
                       (``user_id IS NULL``) plus the signed-in user's own
                       saved contacts.
``save_contact`` /     the user's private address book for a company.
``delete_contact``

``discover_contacts``  a *sourced* web lookup. It runs a Tavily search and
                       returns candidates extracted from real pages, each
                       carrying the URL it was read from and flagged
                       ``verified: false``. Nothing is inferred, guessed from a
                       naming pattern, or generated by a model — if a page does
                       not print an address, no address comes back.

That last rule is deliberate. Fabricating a recruiter name or guessing
``firstname.lastname@company.com`` would produce plausible, confident, wrong
contact details for real people, which is worse than an empty panel.
"""

from __future__ import annotations

import logging
import re
import uuid
from typing import Any
from urllib.parse import urlparse

import httpx
from sqlalchemy import select

from config.settings import get_settings
from services.base import parse_uuid
from storage.database import AsyncSessionLocal
from storage.models import Company, CompanyContact

logger = logging.getLogger(__name__)

_TAVILY_URL = "https://api.tavily.com/search"
_TIMEOUT = httpx.Timeout(20.0, connect=5.0)

VALID_KINDS = {"careers_inbox", "careers_page", "recruiter", "referral", "other"}

_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}")

# Local-part tokens that are never a talent contact, matched as whole
# dot/dash/underscore-separated tokens so "usa-sales@" is caught the same way
# "sales@" is.
_NOISE_TOKENS = frozenset({
    "noreply", "no-reply", "donotreply", "do-not-reply", "postmaster",
    "mailer-daemon", "bounce", "abuse", "webmaster", "admin", "sysadmin",
    "root", "security", "vulnerability", "privacy", "legal", "dpo",
    "grievance", "grievances", "nodal", "compliance", "ombudsman", "press",
    "media", "pr", "newsroom", "communications", "marketing", "partnerships",
    "sales", "presales", "enquiry", "enquiries", "info", "contact", "hello",
    "hi", "support", "help", "care", "customercare", "service", "servicedesk",
    "escalation", "escalations", "billing", "invoice", "invoices", "accounts",
    "finance", "refund", "refunds", "payments", "newsletter", "unsubscribe",
    "notifications", "alerts", "noc", "api", "dev", "devops", "ops", "sre",
})

# Lead-generation and contact-broker sites publish *email format patterns* and
# resold personal data rather than anything the company itself put out. Their
# "contacts" are the fabrication problem laundered through a third party, so
# results from these hosts are dropped before extraction.
_BROKER_DOMAINS = frozenset({
    "leadiq.com", "contactout.com", "rocketreach.co", "zoominfo.com",
    "apollo.io", "lusha.com", "signalhire.com", "hunter.io", "snov.io",
    "findymail.com", "clearbit.com", "kaspr.io", "cognism.com", "uplead.com",
    "adapt.io", "seamless.ai", "lead411.com", "skrapp.io", "anymailfinder.com",
    "voilanorbert.com", "getprospect.com", "emailhippo.com", "salesql.com",
    "wiza.co", "datanyze.com", "slintel.com",
})

# Placeholder local parts. These are format examples ("first.last@acme.com"),
# not people, and they are exactly what a naming-pattern guess would produce.
_PLACEHOLDER_LOCALPARTS = frozenset({
    "first", "last", "firstname", "lastname", "firstinitial", "name",
    "yourname", "username", "user", "email", "youremail", "john", "jane",
    "doe", "johndoe", "janedoe", "example", "sample", "test", "testing",
    "abc", "xyz", "someone", "somebody", "anyone",
})
_PLACEHOLDER_PATTERN = re.compile(
    r"^(first|last|f|l|firstname|lastname|initial|john|jane|j|d|doe)"
    r"[._\-]"
    r"(first|last|f|l|firstname|lastname|initial|john|jane|j|d|doe|name)$",
    re.IGNORECASE,
)

_NOISE_DOMAINS = frozenset({
    "example.com", "example.org", "sentry.io", "wixpress.com", "domain.com",
    "email.com", "yourcompany.com", "company.com",
})

# Local parts that announce themselves as a hiring channel.
_TALENT_LOCALPART = re.compile(
    r"^(careers?|jobs?|hiring|recruit\w*|talent\w*|hr|people|placements?|"
    r"campus|internships?|apply|resume|cv)([._\-]|$)",
    re.IGNORECASE,
)

# A page that is actually about hiring. A personal address only counts as a
# recruiter contact when it was found on one of these — otherwise the grievance
# officer on a redressal page and the PR lead on a newsroom page both get
# mislabelled as recruiters, which is how this went wrong the first time.
_HIRING_PAGE_RE = re.compile(
    r"(career|job|hiring|recruit|vacanc|opening|talent|campus|internship|"
    r"placement|work-with-us|join-us|joinus|life-at|"
    # Applicant tracking systems: the whole host exists to post roles.
    r"greenhouse\.io|lever\.co|ashbyhq\.com|myworkdayjobs\.com|"
    r"smartrecruiters\.com|jobvite\.com|icims\.com|taleo\.net|"
    r"bamboohr\.com|recruitee\.com|workable\.com|darwinbox\.|zohorecruit\.)",
    re.IGNORECASE,
)


def _root_domain(value: str | None) -> str:
    """'https://www.razorpay.com/jobs' or 'razorpay.com' -> 'razorpay.com'."""
    if not value:
        return ""
    host = value if "//" not in value else (urlparse(value).hostname or "")
    # removeprefix, not lstrip — lstrip("www.") would eat the 'w' off "wework.com".
    return host.lower().removeprefix("www.")


def is_broker_source(url: str | None) -> bool:
    """True for contact-reseller hosts whose pages must not be mined at all."""
    host = _root_domain(url)
    return any(host == b or host.endswith(f".{b}") for b in _BROKER_DOMAINS)


def is_hiring_page(url: str | None, title: str | None = None) -> bool:
    """True when a page looks like it is about hiring rather than anything else."""
    return bool(_HIRING_PAGE_RE.search(f"{url or ''} {title or ''}"))


def _is_placeholder(local: str) -> bool:
    """True for format examples like 'first.last' or 'john.doe' — never a person."""
    return local in _PLACEHOLDER_LOCALPARTS or bool(_PLACEHOLDER_PATTERN.match(local))


def _is_noise(local: str) -> bool:
    """
    True when the local part is a non-talent function address.

    Checks the whole local part *and* each of its tokens: the set holds both
    single words ("sales", matching "usa-sales") and hyphenated ones
    ("no-reply"), and splitting first would make the latter unmatchable.
    """
    if local in _NOISE_TOKENS:
        return True
    return bool(_NOISE_TOKENS.intersection(re.split(r"[._\-]+", local)))


def _classify(
    email: str,
    company_domain: str,
    *,
    hiring_context: bool = False,
) -> str | None:
    """
    Return a contact ``kind`` for a talent-looking address, else ``None``.

    Two ways in, and nothing else qualifies:

    * the local part names a hiring channel (``careers@``, ``talent@``) — a
      shared inbox the company published;
    * the address is on the company's own domain **and** it was found on a page
      about hiring, which makes it a plausible recruiter rather than whoever
      happened to be printed on a privacy notice.

    ``hiring_context`` is what the second rule turns on, so callers must pass it
    from the page the address came from.
    """
    local, _, domain = email.partition("@")
    local, domain = local.lower(), domain.lower()

    if domain in _NOISE_DOMAINS or _is_placeholder(local) or _is_noise(local):
        return None
    if _TALENT_LOCALPART.match(local):
        return "careers_inbox"
    if hiring_context and company_domain and (
        domain == company_domain or domain.endswith(f".{company_domain}")
    ):
        return "recruiter"
    return None


def _extract(
    text: str,
    company_domain: str,
    *,
    hiring_context: bool = False,
) -> list[tuple[str, str]]:
    """Pull (email, kind) pairs out of one page's text."""
    found: list[tuple[str, str]] = []
    for raw in _EMAIL_RE.findall(text or ""):
        email = raw.strip(" .,;:)»").lower()
        kind = _classify(email, company_domain, hiring_context=hiring_context)
        if kind:
            found.append((email, kind))
    return found


async def discover_contacts(
    company_id: str,
    *,
    max_results: int = 8,
) -> dict[str, Any]:
    """
    Search the public web for the company's talent contacts.

    Returns ``{"company": ..., "candidates": [...], "queries": [...],
    "available": bool, "message": str|None}``. Every candidate carries the
    ``source_url`` it was read from and ``verified: false``; the caller decides
    whether to save it. An unconfigured Tavily key yields ``available: False``
    rather than an error — the panel just says the lookup is switched off.
    """
    session = AsyncSessionLocal()
    try:
        company = await session.get(Company, parse_uuid(company_id))
        if company is None:
            return {"company": None, "candidates": [], "queries": [],
                    "available": False, "message": "Company not found"}
        name = company.name
        domain = _root_domain(company.domain or company.website_url)
        careers_url = company.careers_url
    finally:
        await session.close()

    api_key = get_settings().tavily_api_key
    if not api_key:
        return {
            "company": name,
            "candidates": [],
            "queries": [],
            "available": False,
            "message": "Web lookup is off — set TAVILY_API_KEY to enable it.",
        }

    queries = [
        f'"{name}" careers page contact email apply India',
        f'"{name}" hiring recruitment contact email Bengaluru jobs',
    ]
    if domain:
        queries.append(f'"{name}" careers OR jobs OR hiring email site:{domain}')

    seen: dict[str, dict[str, Any]] = {}
    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        for query in queries:
            try:
                resp = await client.post(
                    _TAVILY_URL,
                    json={
                        "api_key": api_key,
                        "query": query,
                        "search_depth": "advanced",
                        "max_results": max_results,
                        "include_raw_content": True,
                    },
                )
                resp.raise_for_status()
                results = resp.json().get("results", [])
            except (httpx.HTTPError, ValueError) as exc:
                logger.warning("Tavily contact lookup failed for %r: %s", name, exc)
                continue

            for item in results:
                url = (item.get("url") or "").strip()
                if not url or is_broker_source(url):
                    # Broker pages list email *patterns* and resold personal
                    # data; mining them would reintroduce exactly the guessed
                    # addresses this lookup exists to avoid.
                    continue
                title = item.get("title")
                body = f"{item.get('content') or ''}\n{item.get('raw_content') or ''}"
                hiring = is_hiring_page(url, title)
                for email, kind in _extract(body, domain, hiring_context=hiring):
                    # Keep the first page an address was seen on as its source.
                    if email in seen:
                        continue
                    seen[email] = {
                        "kind": kind,
                        "name": None,
                        "title": None,
                        "email": email,
                        "linkedin_url": None,
                        "source_url": url,
                        "source_title": title,
                        "verified": False,
                        "on_company_domain": bool(domain and email.endswith(f"@{domain}")),
                    }

    candidates = sorted(
        seen.values(),
        key=lambda c: (not c["on_company_domain"], c["kind"] != "careers_inbox", c["email"]),
    )
    message = None
    if not candidates:
        message = (
            f"No published talent address turned up for {name}. Only addresses "
            "printed on real hiring pages count here — pattern guesses from "
            "contact-broker sites are discarded — and most companies route "
            "hiring through their careers page rather than an inbox."
        )
    return {
        "company": name,
        "careers_url": careers_url,
        "candidates": candidates,
        "queries": queries,
        "available": True,
        "message": message,
    }


def _serialise(contact: CompanyContact) -> dict[str, Any]:
    return {
        "id": str(contact.id),
        "kind": contact.kind,
        "name": contact.name,
        "title": contact.title,
        "email": contact.email,
        "linkedin_url": contact.linkedin_url,
        "notes": contact.notes,
        "source_url": contact.source_url,
        "verified": contact.verified,
        "is_curated": contact.user_id is None,
        "created_at": contact.created_at.isoformat() if contact.created_at else None,
    }


async def list_contacts(company_id: str, user_id: str | None) -> list[dict[str, Any]]:
    """Curated public contacts plus this user's private ones, curated first."""
    cid = parse_uuid(company_id)
    if cid is None:
        return []
    uid = parse_uuid(user_id)
    session = AsyncSessionLocal()
    try:
        stmt = select(CompanyContact).where(CompanyContact.company_id == cid)
        if uid is not None:
            stmt = stmt.where(
                (CompanyContact.user_id.is_(None)) | (CompanyContact.user_id == uid)
            )
        else:
            stmt = stmt.where(CompanyContact.user_id.is_(None))
        rows = (await session.execute(stmt.order_by(CompanyContact.created_at))).scalars().all()
        return sorted(
            (_serialise(r) for r in rows),
            key=lambda c: (not c["is_curated"], c["kind"] != "careers_page"),
        )
    finally:
        await session.close()


async def save_contact(
    company_id: str,
    user_id: str,
    *,
    kind: str = "recruiter",
    name: str | None = None,
    title: str | None = None,
    email: str | None = None,
    linkedin_url: str | None = None,
    notes: str | None = None,
    source_url: str | None = None,
    verified: bool = False,
) -> dict[str, Any] | None:
    """
    Store a contact in the user's private list for this company.

    Returns ``None`` when the company does not exist. Raises ``ValueError`` if
    the contact carries no way to actually reach anyone.
    """
    cid, uid = parse_uuid(company_id), parse_uuid(user_id)
    if cid is None or uid is None:
        return None
    if not (email or linkedin_url or name):
        raise ValueError("A contact needs at least a name, an email or a LinkedIn URL.")
    if email and not _EMAIL_RE.fullmatch(email.strip()):
        raise ValueError(f"{email!r} is not a valid email address.")

    session = AsyncSessionLocal()
    try:
        if await session.get(Company, cid) is None:
            return None
        contact = CompanyContact(
            id=uuid.uuid4(),
            company_id=cid,
            user_id=uid,
            kind=kind if kind in VALID_KINDS else "other",
            name=name,
            title=title,
            email=email.strip().lower() if email else None,
            linkedin_url=linkedin_url,
            notes=notes,
            source_url=source_url,
            verified=verified,
        )
        session.add(contact)
        await session.commit()
        await session.refresh(contact)
        return _serialise(contact)
    finally:
        await session.close()


async def delete_contact(contact_id: str, user_id: str) -> bool:
    """
    Delete one of the user's own contacts. Curated entries (``user_id IS NULL``)
    are shared, so they are never deletable through this path.
    """
    cid, uid = parse_uuid(contact_id), parse_uuid(user_id)
    if cid is None or uid is None:
        return False
    session = AsyncSessionLocal()
    try:
        contact = await session.get(CompanyContact, cid)
        if contact is None or contact.user_id != uid:
            return False
        await session.delete(contact)
        await session.commit()
        return True
    finally:
        await session.close()
