"""
services/public_roles.py
~~~~~~~~~~~~~~~~~~~~~~~~
What TalentRadar shows someone who has no account.

Three read-only things: a role's public page, a company's open roles, and the
check that takes a posting URL and says whether it is still open. These are
how a stranger arrives, so they are built to be statically regenerated by the
frontend - nothing here is called on a visitor's page load.

Two rules hold for everything in this module:

* **Only republishable rows.** A public page is built only from postings that
  came from an employer's own ATS API (Greenhouse, Lever, Ashby), which those
  employers publish for exactly this purpose. Rows scraped from job boards
  stay inside the signed-in product.
* **India only.** The product is an India-only board, so a public page needs a
  location that positively resolves to India. Search keeps rows with no stated
  location because a signed-in user can judge them; a public page is a claim
  made to a stranger, and "Remote" with nothing else is not enough for one.
* **No user data, by construction.** ``public_role`` names every field it
  emits. Nothing is spread in from the ORM row, so a column added to ``jobs``
  later cannot leak onto a public page by default.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

from domain.geo import INDIA_COUNTRY_VALUES, is_india
from domain.liveness import is_verifiable_source, title_key
from domain.posting_urls import (
    PostingRef,
    company_slug,
    parse_posting_url,
    role_slug,
    slug_job_id,
)
from ingestion.scrapers.ats_scraper import ATSScraper, PostingCheck
from services import liveness

logger = logging.getLogger(__name__)

MAX_LISTED_ROLES = 2000
MAX_COMPANY_ROLES = 60

_UNSUPPORTED_MESSAGE = (
    "We can only confirm postings hosted on Greenhouse, Lever or Ashby, where the "
    "employer publishes a feed we can ask. For any other site, check the posting "
    "date, whether the company's own careers page lists the role, and whether the "
    "same role keeps reappearing."
)


def is_publishable_source(source: str | None) -> bool:
    """True for rows that came from an employer's own ATS API."""
    text = source or ""
    return ":" in text and is_verifiable_source(text)


def _is_in_india(job: Any) -> bool:
    """True only when the row carries a positive signal that it is in India."""
    if getattr(job, "country", None) in INDIA_COUNTRY_VALUES:
        return True
    return is_india(getattr(job, "location_raw", None)) or is_india(getattr(job, "city", None))


def is_publishable_role(job: Any) -> bool:
    """The one gate every public read goes through: an employer's own ATS, in India."""
    return is_publishable_source(getattr(job, "source", None)) and _is_in_india(job)


def _iso(value: datetime | None) -> str | None:
    return value.isoformat() if value else None


def _company_public_slug(name: str | None, company_id: Any) -> str | None:
    if not company_id:
        return None
    words = company_slug(name)
    return f"{words}-{company_id}" if words else str(company_id)


def public_role(job: Any, sighting: Any | None, *, now: datetime) -> dict[str, Any]:
    """The public view of one role. Every emitted field is named here."""
    company = getattr(job, "company", None)
    company_name = getattr(company, "name", None)
    verdict = liveness.verdict_for(job, sighting, now=now)
    return {
        "id": str(job.id),
        "slug": role_slug(job.title, company_name, job.id),
        "title": job.title,
        "company": company_name,
        "company_slug": _company_public_slug(company_name, job.company_id),
        "location": job.location_raw or job.city,
        "is_remote": bool(job.is_remote),
        "skills": list(job.skills or [])[:12],
        "employment_type": job.employment_type.value if job.employment_type else None,
        "seniority": job.seniority.value if job.seniority else None,
        "source_url": job.source_url,
        "posted_at": _iso(job.source_posted_at),
        "closed_at": _iso(job.closed_at),
        "liveness": liveness.verdict_to_dict(verdict),
    }


# ── reads ────────────────────────────────────────────────────────────────────


async def _role_payload(session: Any, job: Any) -> dict[str, Any]:
    sightings = await liveness.sightings_for(session, [(job.company_id, job.title)])
    return public_role(
        job, sightings.get((job.company_id, title_key(job.title))), now=datetime.now(UTC)
    )


async def get_role(slug: str) -> dict[str, Any] | None:
    """The public role a slug points at, or ``None``."""
    job_id = slug_job_id(slug)
    if job_id is None:
        return None

    from sqlalchemy import select
    from sqlalchemy.orm import selectinload

    from storage.database import AsyncSessionLocal
    from storage.models import Job

    async with AsyncSessionLocal() as session:
        job = (
            await session.execute(
                select(Job).where(Job.id == job_id).options(selectinload(Job.company))
            )
        ).scalar_one_or_none()
        if job is None or not is_publishable_role(job):
            return None
        return await _role_payload(session, job)


async def list_roles(limit: int = 500) -> list[dict[str, Any]]:
    """Slugs of open, publishable roles - what the sitemap and static build read."""
    from sqlalchemy import or_, select
    from sqlalchemy.orm import selectinload

    from storage.database import AsyncSessionLocal
    from storage.models import Job

    async with AsyncSessionLocal() as session:
        jobs = (
            await session.execute(
                select(Job)
                .where(
                    Job.closed_at.is_(None),
                    or_(
                        Job.source.like("greenhouse:%"),
                        Job.source.like("lever:%"),
                        Job.source.like("ashby:%"),
                    ),
                )
                .options(selectinload(Job.company))
                .order_by(Job.last_seen_at.desc().nulls_last())
                .limit(MAX_LISTED_ROLES)
            )
        ).scalars()
        # The India rule is applied here rather than in SQL so that it is the
        # same function every other public read uses; the row cap above keeps
        # the over-fetch bounded.
        wanted = max(1, min(limit, MAX_LISTED_ROLES))
        return [
            {
                "slug": role_slug(job.title, getattr(job.company, "name", None), job.id),
                "title": job.title,
                "company": getattr(job.company, "name", None),
                "location": job.location_raw or job.city,
                "updated_at": _iso(job.last_seen_at or job.updated_at),
            }
            for job in [j for j in jobs if is_publishable_role(j)][:wanted]
        ]


async def company_roles(slug: str) -> dict[str, Any] | None:
    """A company's publishable roles, open ones first, with their verdicts."""
    company_id = slug_job_id(slug)
    if company_id is None:
        return None

    from sqlalchemy import or_, select
    from sqlalchemy.orm import selectinload

    from storage.database import AsyncSessionLocal
    from storage.models import Company, Job

    async with AsyncSessionLocal() as session:
        company = await session.get(Company, company_id)
        if company is None:
            return None
        jobs = list(
            (
                await session.execute(
                    select(Job)
                    .where(
                        Job.company_id == company_id,
                        or_(
                            Job.source.like("greenhouse:%"),
                            Job.source.like("lever:%"),
                            Job.source.like("ashby:%"),
                        ),
                    )
                    .options(selectinload(Job.company))
                    .order_by(Job.closed_at.asc().nulls_first(), Job.source_posted_at.desc().nulls_last())
                    .limit(MAX_COMPANY_ROLES)
                )
            ).scalars()
        )
        jobs = [job for job in jobs if is_publishable_role(job)]
        if not jobs:
            # Nothing of this employer's is publishable, so it has no public page.
            return None
        sightings = await liveness.sightings_for(session, [(j.company_id, j.title) for j in jobs])
        now = datetime.now(UTC)
        roles = [
            public_role(job, sightings.get((job.company_id, title_key(job.title))), now=now)
            for job in jobs
        ]
    return {
        "company": company.name,
        "slug": _company_public_slug(company.name, company.id),
        "open_count": sum(1 for r in roles if not r["closed_at"]),
        "roles": roles,
    }


# ── the check ────────────────────────────────────────────────────────────────


async def _indexed_role_for_ref(ref: PostingRef) -> dict[str, Any] | None:
    from sqlalchemy import select
    from sqlalchemy.orm import selectinload

    from storage.database import AsyncSessionLocal
    from storage.models import Job

    async with AsyncSessionLocal() as session:
        job = (
            await session.execute(
                select(Job)
                .where(Job.source == ref.source, Job.external_id == ref.external_id)
                .options(selectinload(Job.company))
            )
        ).scalar_one_or_none()
        # A role we hold but would not publish is answered from the employer's
        # ATS instead, like any posting we have never seen.
        if job is None or not is_publishable_role(job):
            return None
        # Someone is asking about this posting right now: refresh the evidence
        # before answering rather than repeat a days-old confirmation.
        await liveness.reverify_job(job)
        await session.commit()
        return await _role_payload(session, job)


async def _indexed_role_for_url(url: str) -> dict[str, Any] | None:
    """A publishable role we hold under exactly this URL."""
    from sqlalchemy import select
    from sqlalchemy.orm import selectinload

    from storage.database import AsyncSessionLocal
    from storage.models import Job

    async with AsyncSessionLocal() as session:
        job = (
            await session.execute(
                select(Job)
                .where(Job.source_url == url)
                .options(selectinload(Job.company))
                .limit(1)
            )
        ).scalar_one_or_none()
        if job is None or not is_publishable_role(job):
            return None
        return await _role_payload(session, job)


def _answer(
    status: str, message: str, role: dict[str, Any] | None = None
) -> dict[str, Any]:
    return {
        "status": status,
        "message": message,
        "role": role,
        "liveness": role["liveness"] if role else None,
    }


async def check_url(url: str) -> dict[str, Any]:
    """
    Say what we can about a posting URL. Never raises, and never fetches the
    URL it is given - see ``domain/posting_urls.py``.

    ``status`` is one of:
      indexed      we already track this role; ``liveness`` is its verdict
      open_now     the employer's ATS serves it right now; we have no history
      closed_now   the employer's ATS no longer serves it
      unreachable  a supported ATS, but it could not be asked just now
      unsupported  not a source we can verify
    """
    text = (url or "").strip()
    ref = parse_posting_url(text)

    try:
        role = await (_indexed_role_for_ref(ref) if ref else _indexed_role_for_url(text))
    except Exception as exc:
        logger.debug("Public check could not read the index: %s", exc)
        role = None
    if role is not None:
        return _answer("indexed", role["liveness"]["headline"], role)

    if ref is None:
        return _answer("unsupported", _UNSUPPORTED_MESSAGE)

    try:
        outcome = await ATSScraper.check_posting(ref.source, ref.external_id)
    except Exception as exc:
        logger.debug("Public check could not reach the ATS: %s", exc)
        outcome = PostingCheck.ERROR

    if outcome is PostingCheck.OPEN:
        return _answer(
            "open_now",
            "The employer's careers site is serving this posting right now. We have "
            "not tracked it before, so we cannot say how long it has been open or "
            "whether it has been re-listed.",
        )
    if outcome is PostingCheck.CLOSED:
        return _answer(
            "closed_now", "The employer's careers site no longer serves this posting."
        )
    return _answer(
        "unreachable",
        "We could not reach the employer's careers site just now. Try again in a few minutes.",
    )


__all__ = [
    "check_url",
    "company_roles",
    "get_role",
    "is_publishable_role",
    "is_publishable_source",
    "list_roles",
    "public_role",
]
