'use client'

import { useEffect, useState } from 'react'
import { Brain, Lightbulb, Sparkles } from 'lucide-react'
import AppShell from '@/components/AppShell'
import RequireAuth from '@/components/RequireAuth'
import { api } from '@/lib/api'
import { usePersistentState } from '@/lib/persistent-state'

export default function AgentPage() { const [action, setAction] = useState<Record<string, unknown> | null>(null); const [memories, setMemories] = useState<Array<Record<string, unknown>>>([]); const [learning, setLearning] = usePersistentState<Record<string, unknown> | null>('agent.learning', null); const [error, setError] = useState(''); useEffect(() => { Promise.all([api.agent.nextAction(), api.agent.memories()]).then(([next, stored]) => { setAction(next); setMemories(stored.memories) }).catch(err => setError(err instanceof Error ? err.message : 'Could not reach your career copilot.')) }, []); async function recommend() { try { setLearning(await api.career.recommend()) } catch (err) { setError(err instanceof Error ? err.message : 'Could not create learning recommendations.') } } return <RequireAuth><AppShell><section className="page-heading"><p className="eyebrow">PERSONAL CAREER COPILOT</p><h1>Translate activity into the next right action.</h1><p>Your agent uses your profile, applications, and career signals stored by the backend.</p></section>{error && <p className="form-error">{error}</p>}<div className="agent-grid"><section className="panel agent-action"><Brain size={25}/><p className="eyebrow">RECOMMENDED NEXT STEP</p>{action ? <pre className="generated-copy">{JSON.stringify(action, null, 2)}</pre> : <div className="loading-state">Reading your career context…</div>}<button className="primary-button" onClick={recommend}><Lightbulb size={15}/> Generate learning plan</button></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">SAVED CONTEXT</p><h2>What your agent remembers</h2></div><Sparkles size={17}/></div>{memories.length ? <div className="memory-list">{memories.map((memory, index) => <div key={index}><strong>{String(memory.memory_type || 'Note')}</strong><p>{String(memory.content || '')}</p></div>)}</div> : <p className="muted-copy">Your saved preferences and application context will appear here.</p>}</section></div>{learning && <section className="panel learning-result"><p className="eyebrow">LEARNING RECOMMENDATIONS</p><pre className="generated-copy">{JSON.stringify(learning, null, 2)}</pre></section>}</AppShell></RequireAuth> }
