'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '@/components/AppShell'
import RequireAuth from '@/components/RequireAuth'
import { api } from '@/lib/api'

export default function OnboardingPage() { const router = useRouter(); const [name, setName] = useState(''); const [role, setRole] = useState(''); const [location, setLocation] = useState(''); const [skills, setSkills] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await api.profile.save({ full_name: name, target_roles: role ? [role] : [], target_locations: location ? [location] : [], skills: skills.split(',').map(s => s.trim()).filter(Boolean) }); router.push('/dashboard') } catch (err) { setError(err instanceof Error ? err.message : 'Could not save your profile.') } finally { setSaving(false) } } return <RequireAuth><AppShell><section className="form-page"><p className="eyebrow">WELCOME TO TALENTRADAR</p><h1>Tell us where you&apos;re headed.</h1><p className="lead">We&apos;ll use this to tailor searches, match you with roles, and guide your preparation.</p><form className="card-form" onSubmit={submit}><label>Full name<input value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></label><label>Target role<input value={role} onChange={e => setRole(e.target.value)} placeholder="e.g. Product designer" /></label><label>Preferred location<input value={location} onChange={e => setLocation(e.target.value)} placeholder="e.g. Bengaluru or Remote" /></label><label>Core skills <small>Separate with commas</small><input value={skills} onChange={e => setSkills(e.target.value)} placeholder="Figma, Product strategy, Research" /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Create my workspace'}</button></form></section></AppShell></RequireAuth> }
