'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { Bookmark, ExternalLink, MapPin, Search, Sparkles } from 'lucide-react'
import AppShell from '@/components/AppShell'
import { api, Job, signedIn } from '@/lib/api'

export default function SearchPage() {
  const [query, setQuery] = useState(''); const [location, setLocation] = useState(''); const [remote, setRemote] = useState(false); const [jobs, setJobs] = useState<Job[]>([]); const [summary, setSummary] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState<string[]>([])
  async function find(e: FormEvent) { e.preventDefault(); if (!query.trim()) return; setLoading(true); setError(''); try { if (location || remote) { const response = await api.search.structured(query, location, remote); setJobs(response.jobs || []); setSummary(`${response.total} roles found with your filters.`) } else { const response = await api.search.semantic(query); setJobs(response.results || []); setSummary(response.summary || `${response.total_found} roles found for your search.`) } } catch (err) { setError(err instanceof Error ? err.message : 'Search could not be completed.') } finally { setLoading(false) } }
  async function save(job: Job) { if (!signedIn()) { window.location.assign('/login?next=/search'); return } try { await api.applications.create(job.id); setSaved(items => [...items, job.id]) } catch (err) { setError(err instanceof Error ? err.message : 'Could not save role.') } }
  return <AppShell><section className="page-heading"><div><p className="eyebrow">OPPORTUNITY EXPLORER</p><h1>Find roles that fit your direction.</h1><p>Use natural language—our semantic search reads beyond a title match.</p></div></section><form className="search-form" onSubmit={find}><Search size={20}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="e.g. Senior product design roles in fintech, remote-friendly" /><input className="location-input" value={location} onChange={e => setLocation(e.target.value)} placeholder="Location (optional)" /><label className="check-label"><input type="checkbox" checked={remote} onChange={e => setRemote(e.target.checked)} /> Remote</label><button className="primary-button" disabled={loading}>{loading ? 'Searching…' : 'Search roles'}</button></form>{error && <p className="form-error">{error}</p>}{summary && <div className="search-summary"><Sparkles size={17}/><span>{summary}</span></div>}<div className="results-layout"><aside className="search-tips"><p className="eyebrow">SEARCH BETTER</p><strong>Try asking for:</strong><button onClick={() => setQuery('Remote product design roles with AI experience')}>Remote product design roles with AI experience</button><button onClick={() => setQuery('Senior UX researcher positions in Bengaluru')}>Senior UX researcher positions in Bengaluru</button><button onClick={() => setQuery('Frontend jobs at early stage startups')}>Frontend jobs at early-stage startups</button></aside><section className="job-results">{loading && <div className="loading-state">Scanning the talent market…</div>}{!loading && !jobs.length && <div className="empty-state"><Search size={25}/><h2>Start with a conversation.</h2><p>Describe your ideal role, skills, or working style to see relevant opportunities.</p></div>}{jobs.map(job => <article className="job-card" key={job.id}><div className="job-card-top"><div className="company-logo violet">{(job.company_name || job.company || '?').slice(0, 1)}</div><div><h2>{job.title}</h2><p>{job.company_name || job.company || 'Company not listed'}</p></div>{job.match_score != null && <span className="match-pill">{Math.round(job.match_score * (job.match_score <= 1 ? 100 : 1))}% match</span>}</div><div className="job-meta"><span><MapPin size={14}/>{job.location_raw || (job.is_remote ? 'Remote' : 'Location not listed')}</span>{job.is_remote && <span>Remote-friendly</span>}{job.salary_raw && <span>{job.salary_raw}</span>}</div><div className="chips">{(job.skills || []).slice(0, 5).map(skill => <span key={skill}>{skill}</span>)}</div><div className="job-actions"><button className="outline-button" onClick={() => save(job)} disabled={saved.includes(job.id)}><Bookmark size={14}/>{saved.includes(job.id) ? 'Saved' : 'Save to tracker'}</button>{job.source_url && <a className="text-button" href={job.source_url} target="_blank">View original <ExternalLink size={14}/></a>}</div></article>)}</section></div></AppShell>
}
